const $LargeTurbineMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.generator.LargeTurbineMachine")

GTCEuStartupEvents.registry('gtceu:material_icon_set', event => {
    event.create('infinity').parent(GTMaterialIconSet.SHINY)
})

BlockEvents.modification(event => {
  event.modify('#minecraft:logs', block => {
    block.requiredTool(true)
  })
})

StartupEvents.registry('item', event => {
//circuits
    event.create('supracausal_circuit_board').texture('kubejs:item/supracausal_circuit_board').displayName('Supracausal Circuit Board')
    event.create('supracausal_processing_unit').texture('kubejs:item/supracausal_processing_unit').displayName('Supracausal Processing Unit')
    event.create('supracausal_processor').texture('kubejs:item/supracausal_processor').displayName('Supracausal Processor')
    event.create('supracausal_assembly').texture('kubejs:item/supracausal_assembly').displayName('Supracausal Assembly')
    event.create('supracausal_supercomputer').texture('kubejs:item/supracausal_computer').displayName('Supracausal Supercomputer')
    event.create('supracausal_mainframe').texture('kubejs:item/supracausal_mainframe').displayName('Supracausal Mainframe')
//totally-not-microminers
    //event.create('universe_harvester').texture('kubejs:item/universe_harvester').displayName('Universe Harvester')
    //event.create('universe_manipulator').texture('kubejs:item/universe_manipulator').displayName('Universe Manipulator')
    //event.create('universe_disruptor').texture('kubejs:item/universe_disruptor').displayName('Universe Disruptor')
})

GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('atomic_hyperforge')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(9, 9, 1, 0)
        .setProgressBar(GuiTextures.PROGRESS_BAR_REPLICATOR, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.REPLICATOR)
	event.create('fission_reactor')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(1, 1, 1, 1)
        .setProgressBar(GuiTextures.PROGRESS_BAR_REPLICATOR, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ARC)
    event.create('supercritical_steam_turbine')
    	.category('multiblock')
    	.setEUIO('out')
    	.setMaxIOSize(0, 0, 1, 1)
    	.setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
    	.setSound(GTSoundEntries.TURBINE)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('atomic_hyperforge', 'multiblock')
        //.tooltips(Component.translatable('Bend reality to your whims'))
        .rotationState(RotationState.NON_Y_AXIS)
        .appearanceBlock(GTBlocks.FUSION_CASING_MK3)
        .recipeTypes(['atomic_hyperforge'])
        .pattern(definition => FactoryBlockPattern.start()
        	.aisle('             ','             ','             ','             ','             ','     RRR     ','     RRR     ','             ','             ','             ','             ','             ')
        	.aisle('             ','             ','             ','             ','             ','   RR   RR   ','   RR   RR   ','             ','             ','             ','             ','             ')
            .aisle('  FFTTTTTFF  ','   H     H   ','   H     H   ','   H     H   ','   H     H   ','  RH     HR  ','  RH     HR  ','   H     H   ','   H     H   ','             ','             ','             ')
            .aisle('  FFTTFTTFF  ','  HN  W  NH  ','  HN  W  NH  ','  HN     NH  ','  HN     NH  ',' RHN     NHR ',' RHN     NHR ','  HN     NH  ','  HN     NH  ','   N     N   ','   N     N   ','   N     N   ')
            .aisle('  TTTTHTTTT  ','             ','             ','             ','             ',' R         R ',' R         R ','             ','             ','             ','             ','             ')
            .aisle('  TTTTHTTTT  ','             ','             ','             ','             ','R           R','R     H     R','      J      ','      J      ','     FHF     ','     WWW     ','      W      ')
            .aisle('  TFHHHHHFT  ','   W  F  W   ','   W     W   ','      H      ','      U      ','R     H     R','R    HHH    R','     JHJ     ','     JHJ     ','     HHH     ','     WFW     ','     WSW     ')
            .aisle('  TTTTHTTTT  ','             ','             ','             ','             ','R           R','R     H     R','      J      ','      J      ','     FHF     ','     WWW     ','      W      ')
            .aisle('  TTTTHTTTT  ','             ','             ','             ','             ',' R         R ',' R         R ','             ','             ','             ','             ','             ')
            .aisle('  FFTTFTTFF  ','  HN  W  NH  ','  HN  C  NH  ','  HN     NH  ','  HN     NH  ',' RHN     NHR ',' RHN     NHR ','  HN     NH  ','  HN     NH  ','   N     N   ','   N     N   ','   N     N   ')
            .aisle('  FFTTTTTFF  ','   H     H   ','   H     H   ','   H     H   ','   H     H   ','  RH     HR  ','  RH     HR  ','   H     H   ','   H     H   ','             ','             ','             ')
            .aisle('             ','             ','             ','             ','             ','   RR   RR   ','   RR   RR   ','             ','             ','             ','             ','             ')
            .aisle('             ','             ','             ','             ','             ','     RRR     ','     RRR     ','             ','             ','             ','             ','             ')
            .where('C', Predicates.controller(Predicates.blocks(definition.get())))
            .where('S', Predicates.abilities(PartAbility.MUFFLER))
            .where('N', Predicates.blocks(GTBlocks.COIL_NAQUADAH.get()))
            .where('R', Predicates.blocks(GTBlocks.COIL_TRITANIUM.get()))
            .where('T', Predicates.blocks('gtceu:high_temperature_smelting_casing'))
            .where('J', Predicates.blocks('gtceu:fusion_coil'))
            .where('F', Predicates.blocks('gtceu:fusion_casing_mk3'))
            .where('H', Predicates.blocks('gtceu:high_power_casing'))
            .where('U', Predicates.blocks('gtceu:uhv_ultimate_battery'))
            .where(' ', Predicates.any())
            .where('W', Predicates.blocks('gtceu:fusion_casing_mk3')
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
        .build())
        .workableCasingModel(
            "gtceu:block/casings/fusion/fusion_casing_mk3",
            "gtceu:block/multiblock/large_chemical_reactor"
        )
    event.create('fission_reactor', 'multiblock')
    	.rotationState(RotationState.ALL)
    	.appearanceBlock(GTBlocks.CASING_TITANIUM_STABLE)
    	.recipeTypes(['fission_reactor'])
    	.pattern(definition => FactoryBlockPattern.start()
			.aisle(' WWW ',' WVW ',' TVT ',' TVT ',' TVT ','  W  ')
			.aisle('WWWWW','WP PW','TP PT','TP PT','TP PT',' GWG ')
			.aisle('WWWWW','V P V','V P V','V P V','V P V','WWGWW')
			.aisle('WWWWW','WP PW','TP PT','TP PT','TP PT',' GWG ')
			.aisle(' WWW ',' WCW ',' TVT ',' TVT ',' TVT ','  W  ')
			.where('C', Predicates.controller(Predicates.blocks(definition.get())))
			.where(' ', Predicates.any())
			.where('W', Predicates.blocks('gtceu:stable_machine_casing')
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
			.where('V', Predicates.blocks('gtceu:engine_intake_casing'))
			.where('P', Predicates.blocks('gtceu:titanium_pipe_casing'))
			.where('T', Predicates.blocks('gtceu:stable_machine_casing'))
			.where('G', Predicates.blocks('gtceu:titanium_gearbox'))
    		.build())
    	.workableCasingModel(
    		"gtceu:block/casings/solid/machine_casing_stable_titanium",
    		"gtceu:block/multiblock/large_chemical_reactor"
    	)
    /*
    event.create('supercritical_steam_turbine','multiblock')
    	.rotationState(RotationState.ALL)
    	.machine((holder) => new $LargeTurbineMachine(holder, GTValues.EV))
    	.recipeTypes(['supercritical_steam_turbine'])
    	.recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT_SUBTICK, (machine, recipe) => GTRecipeModifiers.LargeTurbineMachine(machine, recipe)])
    	.appearanceBlock(GTBlocks.CASING_TITANIUM_TURBINE)
    	.pattern(definition => FactoryBlockPattern.start()
			.aisle('TTTT','TWWT','TTTT')
			.aisle('TWWT','RGGD','TWWT')
			.aisle('TTTT','TCWT','TTTT')
			.where('T', Predicates.blocks('gtceu:titanium_turbine_casing'))
			.where('G', Predicates.blocks('gtceu:titanium_gearbox'))
			.where('W', Predicates.blocks('gtceu:titanium_turbine_casing')
				.or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
				.or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
				.or(Predicates.abilities(PartAbility.MUFFLER).setExactLimit(1)))
			.where('C', Predicates.controller(Predicates.blocks(definition.get())))
			.where('R', Predicates.ability(PartAbility.ROTOR_HOLDER).setExactLimit(1))
			.where('D', Predicates.abilities(PartAbility.OUTPUT_ENERGY).setExactLimit(1)
				.or(Predicates.abilities(PartAbility.SUBSTATION_OUTPUT_ENERGY).setExactLimit(1)))
			.build())
		.workableCasingModel(
			"gtceu:block/casings/mechanic/machine_casing_turbine_titanium",
			"gtceu:block/multiblock/generator/large_gas_turbine"
		)
	*/
})
