ServerEvents.recipes(event => {
    event.remove({id:'gtceu:shaped/steel_bricks_hull'})
    event.remove({id:'gtceu:shaped/steel_hull'})
    event.remove({id:'gtceu:shaped/bronze_bricks_hull'})
    event.remove({id:'gtceu:shaped/bronze_hull'})
    event.remove({id:'gtceu:shaped/steam_boiler_coal_bronze'})
    event.remove({id:'gtceu:shaped/steam_boiler_lava_bronze'})
    event.remove({id:'gtceu:shaped/steam_boiler_solar_bronze'})
    event.remove({id:'gtceu:shaped/steam_boiler_coal_steel'})
    event.remove({id:'gtceu:shaped/steam_boiler_lava_steel'})
    event.remove({id:'gtceu:shaped/steam_boiler_solar_steel'})
})
